
all: make

new:
	cd build;\
	cmake .;\
  make
make:
	cd build;\
	make

run:
	./LumaxEngine

debug:
	/usr/local/Cellar/gdb/8.0.1/bin/gdb LumaxEngine

clean:
	rm -rf *.o
	rm -rf *.out
	rm -rf *.obj
	rm -r build/*
