
#include "buildDesc.hpp"

#ifdef _USE_DIRECTINPUT
#include "DirectInput.hpp"
#elif defined _USE_GLFW
#include "UsingOpenGL.hpp"
#endif

#ifdef _USE_GLFW
#define LMX_KEY_A GLFW_KEY_A
#define LMX_KEY_B GLFW_KEY_B
#define LMX_KEY_C GLFW_KEY_C
#define LMX_KEY_D GLFW_KEY_D
#define LMX_KEY_E GLFW_KEY_E
#define LMX_KEY_F GLFW_KEY_F
#define LMX_KEY_G GLFW_KEY_G
#define LMX_KEY_H GLFW_KEY_H
#define LMX_KEY_I GLFW_KEY_I
#define LMX_KEY_J GLFW_KEY_J
#define LMX_KEY_K GLFW_KEY_K
#define LMX_KEY_L GLFW_KEY_L
#define LMX_KEY_M GLFW_KEY_M
#define LMX_KEY_N GLFW_KEY_N
#define LMX_KEY_O GLFW_KEY_O
#define LMX_KEY_P GLFW_KEY_P
#define LMX_KEY_Q GLFW_KEY_Q
#define LMX_KEY_R GLFW_KEY_R
#define LMX_KEY_S GLFW_KEY_S
#define LMX_KEY_T GLFW_KEY_T
#define LMX_KEY_U GLFW_KEY_U
#define LMX_KEY_V GLFW_KEY_V
#define LMX_KEY_W GLFW_KEY_W
#define LMX_KEY_X GLFW_KEY_X
#define LMX_KEY_Y GLFW_KEY_Y
#define LMX_KEY_Z GLFW_KEY_Z
#define LMX_KEY_0 GLFW_KEY_0
#define LMX_KEY_1 GLFW_KEY_1
#define LMX_KEY_2 GLFW_KEY_2
#define LMX_KEY_3 GLFW_KEY_3
#define LMX_KEY_4 GLFW_KEY_4
#define LMX_KEY_5 GLFW_KEY_5
#define LMX_KEY_6 GLFW_KEY_6
#define LMX_KEY_7 GLFW_KEY_7
#define LMX_KEY_8 GLFW_KEY_8
#define LMX_KEY_9 GLFW_KEY_9
#define LMX_KEY_ESCAPE GLFW_KEY_ESCAPE
#define LMX_KEY_SPACE GLFW_KEY_SPACE
#define LMX_KEY_MINUS GLFW_KEY_MINUS
#define LMX_KEY_EQUAL GLFW_KEY_EQUAL
#define LMX_KEY_BACKSPACE GLFW_KEY_BACKSPACE
#define LMX_KEY_TAB GLFW_KEY_TAB
#define LMX_KEY_LBRACKET GLFW_KEY_LEFT_BRACKET
#define LMX_KEY_RBRACKET GLFW_KEY_RIGHT_BRACKET
#define LMX_KEY_SEMICOLON GLFW_KEY_SEMICOLON
#define LMX_KEY_ENTER GLFW_KEY_ENTER
#define LMX_KEY_APOSTROPHE GLFW_KEY_APOSTROPHE
#define LMX_KEY_COMMA GLFW_KEY_COMMA
#define LMX_KEY_PERIOD GLFW_KEY_PERIOD
#define LMX_KEY_SLASH GLFW_KEY_SLASH
#define LMX_KEY_F1 GLFW_KEY_F1
#define LMX_KEY_F2 GLFW_KEY_F2
#define LMX_KEY_F3 GLFW_KEY_F3
#define LMX_KEY_F4 GLFW_KEY_F4
#define LMX_KEY_F5 GLFW_KEY_F5
#define LMX_KEY_F6 GLFW_KEY_F6
#define LMX_KEY_F7 GLFW_KEY_F7
#define LMX_KEY_F8 GLFW_KEY_F8
#define LMX_KEY_F9 GLFW_KEY_F9
#define LMX_KEY_F10 GLFW_KEY_F10
#define LMX_KEY_F11 GLFW_KEY_F11
#define LMX_KEY_F12 GLFW_KEY_F12
#define LMX_KEY_CAPSLOCK GLFW_KEY_CAPS_LOCK
#define LMX_KEY_MINUS_NUMPAD GLFW_KEY_KP_SUBTRACT
#define LMX_KEY_PLUS_NUMPAD GLFW_KEY_KP_ADD
#define LMX_KEY_ENTER_NUMPAD GLFW_KEY_KP_ENTER
#define LMX_KEY_LSHIFT GLFW_KEY_LEFT_SHIFT
#define LMX_KEY_RSHIFT GLFW_KEY_RIGHT_SHIFT
#define LMX_KEY_SHIFT (GLFW_KEY_LEFT_SHIFT | GLFW_KEY_RIGHT_SHIFT)
#define LMX_KEY_LCTRL GLFW_KEY_LEFT_CONTROL
#define LMX_KEY_RCTRL GLFW_KEY_RIGHT_CONTROL
#define LMX_KEY_CTRL (GLFW_KEY_LEFT_CONTROL | GLFW_KEY_RIGHT_CONTROL)
#define LMX_KEY_LALT GLFW_KEY_LEFT_ALT
#define LMX_KEY_RALT GLFW_KEY_RIGHT_ALT
#define LMX_KEY_ALT (GLFW_KEY_LEFT_ALT | GLFW_KEY_RIGHT_ALT)
#elif defined _USE_DIRECTINPUT
#define LMX_KEY_A DIK_A
#define LMX_KEY_B DIK_B
#define LMX_KEY_C DIK_C
#define LMX_KEY_D DIK_D
#define LMX_KEY_E DIK_E
#define LMX_KEY_F DIK_F
#define LMX_KEY_G DIK_G
#define LMX_KEY_H DIK_H
#define LMX_KEY_I DIK_I
#define LMX_KEY_J DIK_J
#define LMX_KEY_K DIK_K
#define LMX_KEY_L DIK_L
#define LMX_KEY_M DIK_M
#define LMX_KEY_N DIK_N
#define LMX_KEY_O DIK_O
#define LMX_KEY_P DIK_P
#define LMX_KEY_Q DIK_Q
#define LMX_KEY_R DIK_R
#define LMX_KEY_S DIK_S
#define LMX_KEY_T DIK_T
#define LMX_KEY_U DIK_U
#define LMX_KEY_V DIK_V
#define LMX_KEY_W DIK_W
#define LMX_KEY_X DIK_X
#define LMX_KEY_Y DIK_Y
#define LMX_KEY_Z DIK_Z
#define LMX_KEY_0 DIK_0
#define LMX_KEY_1 DIK_1
#define LMX_KEY_2 DIK_2
#define LMX_KEY_3 DIK_3
#define LMX_KEY_4 DIK_4
#define LMX_KEY_5 DIK_5
#define LMX_KEY_6 DIK_6
#define LMX_KEY_7 DIK_7
#define LMX_KEY_8 DIK_8
#define LMX_KEY_9 DIK_9
#define LMX_KEY_ESCAPE DIK_ESCAPE
#define LMX_KEY_SPACE DIK_SPACE
#define LMX_KEY_MINUS DIK_MINUS
#define LMX_KEY_EQUAL DIK_EQUALS
#define LMX_KEY_BACKSPACE DIK_BACK
#define LMX_KEY_TAB DIK_TAB
#define LMX_KEY_LBRACKET DIK_LBRACKET
#define LMX_KEY_RBRACKET DIK_RBRACKET
#define LMX_KEY_SEMICOLON DIK_SEMICOLON
#define LMX_KEY_ENTER DIK_RETURN
#define LMX_KEY_APOSTROPHE DIK_APOSTROPHE
#define LMX_KEY_COMMA DIK_COMMA
#define LMX_KEY_PERIOD DIK_PERIOD
#define LMX_KEY_SLASH DIK_SLASH
#define LMX_KEY_F1 DIK_F1
#define LMX_KEY_F2 DIK_F2
#define LMX_KEY_F3 DIK_F3
#define LMX_KEY_F4 DIK_F4
#define LMX_KEY_F5 DIK_F5
#define LMX_KEY_F6 DIK_F6
#define LMX_KEY_F7 DIK_F7
#define LMX_KEY_F8 DIK_F8
#define LMX_KEY_F9 DIK_F9
#define LMX_KEY_F10 DIK_F10
#define LMX_KEY_F11 DIK_F11
#define LMX_KEY_F12 DIK_F12
#define LMX_KEY_CAPSLOCK DIK_CAPITAL
#define LMX_KEY_MINUS_NUMPAD DIK_SUBTRACT
#define LMX_KEY_PLUS_NUMPAD DIK_ADD
#define LMX_KEY_ENTER_NUMPAD DIK_NUMPADENTER
#define LMX_KEY_LSHIFT DIK_LSHIFT
#define LMX_KEY_RSHIFT DIK_RSHIFT
#define LMX_KEY_SHIFT (DIK_LSHIFT | DIK_RSHIFT)
#define LMX_KEY_LCTRL DIK_LCONTROL
#define LMX_KEY_RCTRL DIK_RCONTROL
#define LMX_KEY_CTRL (DIK_LCONTROL | DIK_RCONTROL)
#define LMX_KEY_LALT DIK_LMENU
#define LMX_KEY_RALT DIK_RMENU
#define LMX_KEY_ALT (DIK_LMENU | DIK_RMENU)
#endif